### ISSUE TITLE
Not `get` methods in interfaces

### ISSUE THREAD

**Issue by magx2** [kbuntrock/openapi-maven-plugin#135]
I found a bug that when an interface has a method named without get prefix it will not show in generated swagger:

This interface

```java
public interface NoGetInterface {
    String foo();
}
```

will produce empty schema:

```yaml
components:
  schemas:
    NoGetInterface:
      type: object
```

where in my opinion it should have foo field, like this:

```yaml
components:
  schemas:
    NoGetInterface:
      type: object
      properties:
        foo:
          type: string
```
